exportFilePath:
  - ./assets/flows/full-basic-vars.json
  - ./assets/flows/full-basic-subflow-1.json
  - ./assets/flows/full-basic-subflow-2.json

validate:
  field: flow_json

generate:
  resource:
    - davinci_flow
    - davinci_variable
    - davinci_connection

  outputPath: ./testoutput
  overwrite: true